name: "HyperJudge-Cpp"

mode: ONCE

clone_newnet: true
clone_newpid: true
clone_newns: true
clone_newipc: true
clone_newuts: true
clone_newuser: true

time_limit: 5
rlimit_cpu: 5
rlimit_as: 256
rlimit_fsize: 10

keep_caps: false
disable_no_new_privs: false

mount {
    src: "/lib"
    dst: "/lib"
    is_bind: true
    rw: false
}

mount {
    src: "/lib64"
    dst: "/lib64"
    is_bind: true
    rw: false
}
mount {
    src: "/home/prajwal311/hyperjudge-test"
    dst: "/home/prajwal311/hyperjudge-test"
    is_bind: true
    rw: false
}