name: "HyperJudge-Execute"

mode: ONCE

clone_newnet: true
clone_newpid: true
clone_newns: true
clone_newipc: true
clone_newuts: true
clone_newuser: true

keep_caps: false
disable_no_new_privs: false

# Execution limit overrides are passed dynamically via CLI.
# Hard limit file creation:
rlimit_fsize: 1

mount {
    src: "/lib"
    dst: "/lib"
    is_bind: true
    rw: false
}

mount {
    src: "/lib64"
    dst: "/lib64"
    is_bind: true
    rw: false
}

mount {
    src: "/usr/lib"
    dst: "/usr/lib"
    is_bind: true
    rw: false
}
