name: "HyperJudge-Compile"

mode: ONCE

clone_newnet: true
clone_newpid: true
clone_newns: true
clone_newipc: true
clone_newuts: true
clone_newuser: true

keep_caps: false
disable_no_new_privs: false

envar: "PATH=/usr/bin:/bin:/usr/local/bin"

# Reasonable limits for the compiler
rlimit_fsize: 100
rlimit_cpu: 15
rlimit_as: 1024
time_limit: 15

mount {
    src: "/lib"
    dst: "/lib"
    is_bind: true
    rw: false
}

mount {
    src: "/lib64"
    dst: "/lib64"
    is_bind: true
    rw: false
}

mount {
    src: "/usr"
    dst: "/usr"
    is_bind: true
    rw: false
}

mount {
    src: "/bin"
    dst: "/bin"
    is_bind: true
    rw: false
}

mount {
    src: "/etc/alternatives"
    dst: "/etc/alternatives"
    is_bind: true
    rw: false
}

mount {
    dst: "/tmp"
    fstype: "tmpfs"
    rw: true
    is_bind: false
    options: "size=100m"
}
